// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/companies/:id": {
    params: {
      "id": string;
    };
  };
  "/sources/:name": {
    params: {
      "name": string;
    };
  };
  "/sources/:name/raw_input": {
    params: {
      "name": string;
    };
  };
  "/sources/:name/pipeline": {
    params: {
      "name": string;
    };
  };
  "/sources/:name/schedule": {
    params: {
      "name": string;
    };
  };
  "/sources/:name/config": {
    params: {
      "name": string;
    };
  };
  "/sources/:name/logs": {
    params: {
      "name": string;
    };
  };
  "/domains/:id": {
    params: {
      "id": string;
    };
  };
  "/companies": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/domains": {
    params: {};
  };
  "/sources": {
    params: {};
  };
  "/review": {
    params: {};
  };
  "/review/financials": {
    params: {};
  };
  "/review/companies": {
    params: {};
  };
  "/review/domains": {
    params: {};
  };
  "/jobs": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/companies/:id" | "/sources/:name" | "/sources/:name/raw_input" | "/sources/:name/pipeline" | "/sources/:name/schedule" | "/sources/:name/config" | "/sources/:name/logs" | "/domains/:id" | "/companies" | "/dashboard" | "/domains" | "/sources" | "/review" | "/review/financials" | "/review/companies" | "/review/domains" | "/jobs";
  };
  "routes/companies_.$id.tsx": {
    id: "routes/companies_.$id";
    page: "/companies/:id";
  };
  "routes/sources_.$name.tsx": {
    id: "routes/sources_.$name";
    page: "/sources/:name" | "/sources/:name/raw_input" | "/sources/:name/pipeline" | "/sources/:name/schedule" | "/sources/:name/config" | "/sources/:name/logs";
  };
  "routes/sources_.$name.raw_input.tsx": {
    id: "routes/sources_.$name.raw_input";
    page: "/sources/:name/raw_input";
  };
  "routes/sources_.$name.pipeline.tsx": {
    id: "routes/sources_.$name.pipeline";
    page: "/sources/:name/pipeline";
  };
  "routes/sources_.$name.schedule.tsx": {
    id: "routes/sources_.$name.schedule";
    page: "/sources/:name/schedule";
  };
  "routes/sources_.$name._index.tsx": {
    id: "routes/sources_.$name._index";
    page: "/sources/:name";
  };
  "routes/sources_.$name.config.tsx": {
    id: "routes/sources_.$name.config";
    page: "/sources/:name/config";
  };
  "routes/sources_.$name.logs.tsx": {
    id: "routes/sources_.$name.logs";
    page: "/sources/:name/logs";
  };
  "routes/domains_.$id.tsx": {
    id: "routes/domains_.$id";
    page: "/domains/:id";
  };
  "routes/companies.tsx": {
    id: "routes/companies";
    page: "/companies";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/domains.tsx": {
    id: "routes/domains";
    page: "/domains";
  };
  "routes/sources.tsx": {
    id: "routes/sources";
    page: "/sources";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/review.tsx": {
    id: "routes/review";
    page: "/review" | "/review/financials" | "/review/companies" | "/review/domains";
  };
  "routes/review.financials.tsx": {
    id: "routes/review.financials";
    page: "/review/financials";
  };
  "routes/review.companies.tsx": {
    id: "routes/review.companies";
    page: "/review/companies";
  };
  "routes/review.domains.tsx": {
    id: "routes/review.domains";
    page: "/review/domains";
  };
  "routes/review._index.tsx": {
    id: "routes/review._index";
    page: "/review";
  };
  "routes/jobs.tsx": {
    id: "routes/jobs";
    page: "/jobs";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/companies_.$id": typeof import("./app/routes/companies_.$id.tsx");
  "routes/sources_.$name": typeof import("./app/routes/sources_.$name.tsx");
  "routes/sources_.$name.raw_input": typeof import("./app/routes/sources_.$name.raw_input.tsx");
  "routes/sources_.$name.pipeline": typeof import("./app/routes/sources_.$name.pipeline.tsx");
  "routes/sources_.$name.schedule": typeof import("./app/routes/sources_.$name.schedule.tsx");
  "routes/sources_.$name._index": typeof import("./app/routes/sources_.$name._index.tsx");
  "routes/sources_.$name.config": typeof import("./app/routes/sources_.$name.config.tsx");
  "routes/sources_.$name.logs": typeof import("./app/routes/sources_.$name.logs.tsx");
  "routes/domains_.$id": typeof import("./app/routes/domains_.$id.tsx");
  "routes/companies": typeof import("./app/routes/companies.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/domains": typeof import("./app/routes/domains.tsx");
  "routes/sources": typeof import("./app/routes/sources.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/review": typeof import("./app/routes/review.tsx");
  "routes/review.financials": typeof import("./app/routes/review.financials.tsx");
  "routes/review.companies": typeof import("./app/routes/review.companies.tsx");
  "routes/review.domains": typeof import("./app/routes/review.domains.tsx");
  "routes/review._index": typeof import("./app/routes/review._index.tsx");
  "routes/jobs": typeof import("./app/routes/jobs.tsx");
};