// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/companies/:id": {
    params: {
      "id": string;
    };
  };
  "/sources/:name": {
    params: {
      "name": string;
    };
  };
  "/domains/:id": {
    params: {
      "id": string;
    };
  };
  "/companies": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/domains": {
    params: {};
  };
  "/sources": {
    params: {};
  };
  "/review": {
    params: {};
  };
  "/jobs": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/companies/:id" | "/sources/:name" | "/domains/:id" | "/companies" | "/dashboard" | "/domains" | "/sources" | "/review" | "/jobs";
  };
  "routes/companies_.$id.tsx": {
    id: "routes/companies_.$id";
    page: "/companies/:id";
  };
  "routes/sources_.$name.tsx": {
    id: "routes/sources_.$name";
    page: "/sources/:name";
  };
  "routes/domains_.$id.tsx": {
    id: "routes/domains_.$id";
    page: "/domains/:id";
  };
  "routes/companies.tsx": {
    id: "routes/companies";
    page: "/companies";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/domains.tsx": {
    id: "routes/domains";
    page: "/domains";
  };
  "routes/sources.tsx": {
    id: "routes/sources";
    page: "/sources";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/review.tsx": {
    id: "routes/review";
    page: "/review";
  };
  "routes/jobs.tsx": {
    id: "routes/jobs";
    page: "/jobs";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/companies_.$id": typeof import("./app/routes/companies_.$id.tsx");
  "routes/sources_.$name": typeof import("./app/routes/sources_.$name.tsx");
  "routes/domains_.$id": typeof import("./app/routes/domains_.$id.tsx");
  "routes/companies": typeof import("./app/routes/companies.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/domains": typeof import("./app/routes/domains.tsx");
  "routes/sources": typeof import("./app/routes/sources.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/review": typeof import("./app/routes/review.tsx");
  "routes/jobs": typeof import("./app/routes/jobs.tsx");
};